### PR TITLE
Fixed skizze-cli from crashing when len(fields) less than 5 while creating domains. Fix #104

### LINKED ISSUE #104: skizze-cli - Missing parameters on command 'create dom' throw 'index out of range' exception
When leaving out the 4th and 5th parameter (e.g. create dom demo) skizze-cli crashes and throws an 'index out of range exception'.

Instead it should display an 'Invalid operation' message.

### PR DESCRIPTION
**Pull request by martinpinto**
Skizze CLI doesn't crash now when the length of the commands for creating domains is less than 5.

### CODE REVIEW

File: src/skizze-cli/bridge/loop.go [hunk 1]
```diff
@@ -57,7 +57,7 @@ EXAMPLES:
   CREATE DOM users 100 100000
   ADD DOM users neil seif martin conor neil conor seif seif seif
   GET FREQ users neil
-  GET RANK users      
+  GET RANK users
```
Comment (martinpinto) [inline src/skizze-cli/bridge/loop.go]: Removed trailing whitespaces. I guess I have a mild case of OCD...

File: src/skizze-cli/bridge/domain.go [hunk 2]
```diff
@@ -14,7 +14,9 @@ import (
 
 func createDomain(fields []string, in *pb.Domain) error {
 	if len(fields) > 5 {
-		return fmt.Errorf("Too many argumets, expected 4 got %d", len(fields))
+		return fmt.Errorf("Too many arguments, expected 4 got %d", len(fields))
+	} else if len(fields) < 5 {
+		return fmt.Errorf("Not enough arguments, expected 5 got %d", len(fields))
 	}
```
Comment (seiflotfy) [inline src/skizze-cli/bridge/domain.go]: Or just one line with if len(fields) != 4
with return fmt.Errorf("Expected 4 got %d", len(fields))

Comment (martinpinto) [inline src/skizze-cli/bridge/domain.go]: will do, should be len(fields) != 5 though

Comment (seiflotfy) [inline src/skizze-cli/bridge/domain.go]: Yes my bad
